name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change to your AWS region

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 061039783209.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t pastebin-app .
          docker tag pastebin-app:latest 061039783209.dkr.ecr.us-east-2.amazonaws.com/pastebin-app:latest
          docker push 061039783209.dkr.ecr.us-east-2.amazonaws.com/pastebin-app:latest

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name pastebin-cluster
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
